service: hilltop-userSettings

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  userSettingsTableName: ${self:custom.stage}-userSettings

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  timeout: 29

  # These environment variables are made available to our functions
  # under process.env.
  environment:
    userSettingsTableName: ${self:custom.userSettingsTableName}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - "Fn::GetAtt": [UserSettingsTable, Arn]

functions:
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /notes
  # - method: POST request
  # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
  #     domain api call
  # - authorizer: authenticate using the AWS IAM role
  update:
    handler: update.main
    events:
      - http:
          path: userSettings
          method: put
          cors: true
          authorizer: aws_iam
  get:
    handler: get.main
    events:
      - http:
          path: userSettings
          method: get
          cors: true
          authorizer: aws_iam

# Create our resources with separate CloudFormation templates
resources:
  # DynamoDB
  - ${file(../../resources/userSettings-table.yml)}
  - Outputs:
      UserSettingsApiGatewayRestApi:
        Value:
          Ref: ApiGatewayRestApi
        Export:
          Name: ${self:custom.stage}-UserSettingsApiGatewayRestApi
