Resources:
  RecordingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.recordingTableName}
      AttributeDefinitions:
        - AttributeName: teamId
          AttributeType: S
        - AttributeName: recordingId
          AttributeType: S
      KeySchema:
        - AttributeName: teamId
          KeyType: HASH
        - AttributeName: recordingId
          KeyType: RANGE

      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST

Outputs:
  RecordingTableArn:
    Value:
      Fn::GetAtt:
        - RecordingTable
        - Arn
    Export:
      Name: ${self:custom.stage}-RecordingTableArn
