Resources:
  RecordingTestTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.recordingTestTableName}
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TimeToLiveSpecification:
        AttributeName: expiration
        Enabled: true
      AttributeDefinitions:
        - AttributeName: teamId
          AttributeType: S
        - AttributeName: recordingId
          AttributeType: S
      KeySchema:
        - AttributeName: teamId
          KeyType: HASH
        - AttributeName: recordingId
          KeyType: RANGE

      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST

Outputs:
  RecordingTestTableArn:
    Value:
      Fn::GetAtt:
        - RecordingTestTable
        - Arn
    Export:
      Name: ${self:custom.stage}-RecordingTestTableArn
