Resources:
  ScreenshotsBucket:
    Type: AWS::S3::Bucket
    Properties:
      # Set the CORS policy
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000

Outputs:
  ScreenshotsBucketName:
    Value:
      Ref: ScreenshotsBucket
    Export:
      Name: ${self:custom.stage}-ScreenshotsBucket

  ScreenshotsBucketArn:
    Value:
      Fn::GetAtt:
        - ScreenshotsBucket
        - Arn
    Export:
      Name: ${self:custom.stage}-ScreenshotsBucketArn
