Resources:
  ScreenshotsBucket:
    Type: AWS::S3::Bucket
    Properties:
      # Set the CORS policy
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - HEAD
            MaxAge: 3000

  ScreenshotsBucketAllowPublicReadPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Principal: "*"
            Effect: Allow
            Action:
              - "s3:GetObject"
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:aws:s3:::"
                    - "Fn::ImportValue": ${self:custom.stage}-ScreenshotsBucket
                    - "/public/*"
              - Fn::Join:
                  - ""
                  - - "arn:aws:s3:::"
                    - "Fn::ImportValue": ${self:custom.stage}-ScreenshotsBucket
                    - "/*"
      Bucket:
        Ref: ScreenshotsBucket

Outputs:
  ScreenshotsBucketName:
    Value:
      Ref: ScreenshotsBucket
    Export:
      Name: ${self:custom.stage}-ScreenshotsBucket

  ScreenshotsBucketArn:
    Value:
      Fn::GetAtt:
        - ScreenshotsBucket
        - Arn
    Export:
      Name: ${self:custom.stage}-ScreenshotsBucketArn
