Resources:
  UserSettingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.userSettingsTableName}
      AttributeDefinitions:
        - AttributeName: teamId
          AttributeType: S
      KeySchema:
        - AttributeName: teamId
          KeyType: HASH

      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST

Outputs:
  RecordingTableArn:
    Value:
      Fn::GetAtt:
        - UserSettingsTable
        - Arn
    Export:
      Name: ${self:custom.stage}-UserSettingsArn
