Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.userTableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: teamId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: teamId
          KeyType: RANGE

      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST

Outputs:
  UserTableArn:
    Value:
      Fn::GetAtt:
        - UserTable
        - Arn
    Export:
      Name: ${self:custom.stage}-UserTableArn
