service: hilltop-user-api

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  userTableName: ${self:custom.stage}-users

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  timeout: 29

  # These environment variables are made available to our functions
  # under process.env.
  environment:
    userTableName: ${self:custom.userTableName}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - "Fn::GetAtt": [UserTable, Arn]

functions:
  update:
    handler: update.main
    events:
      - http:
          path: update
          method: put
          cors: true
          authorizer: aws_iam
  get:
    handler: get.main
    events:
      - http:
          path: get
          method: get
          cors: true
          authorizer: aws_iam

# Create our resources with separate CloudFormation templates
resources:
  # DynamoDB
  - ${file(../../resources/user-table.yml)}
  - Outputs:
      UserApiGatewayRestApi:
        Value:
          Ref: ApiGatewayRestApi
        Export:
          Name: ${self:custom.stage}-UserApiGatewayRestApi
