service: hilltop-user-api

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  userTableName: ${self:custom.stage}-users
  userPoolId:
    "Fn::ImportValue": ${self:custom.stage}-UserPoolId

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  timeout: 29

  environment:
    userTableName: ${self:custom.userTableName}
    userPoolId: ${self:custom.userPoolId}

  iamRoleStatements:
    - Action:
        - cognito-idp:AdminGetUser
        - cognito-idp:AdminCreateUser
      Resource:
        - "Fn::ImportValue": ${self:custom.stage}-UserPoolArn
      Effect: Allow
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - "Fn::GetAtt": [UserTable, Arn]

functions:
  update:
    handler: update.main
    events:
      - http:
          path: update
          method: put
          cors: true
          authorizer: aws_iam
  get:
    handler: get.main
    events:
      - http:
          path: get
          method: get
          cors: true
          authorizer: aws_iam

  getTeam:
    handler: getTeam.main
    events:
      - http:
          path: getTeam
          method: get
          cors: true
          authorizer: aws_iam

  activate:
    handler: activate.main
    events:
      - http:
          path: activate
          method: post
          cors: true
          authorizer: aws_iam

  create:
    handler: create.main
    events:
      - http:
          path: create
          method: post
          cors: true
          authorizer: aws_iam

  createNewUser:
    handler: createNewUser.main
    events:
      - http:
          path: createNewUser
          method: post
          cors: true
          authorizer: aws_iam

# Create our resources with separate CloudFormation templates
resources:
  # DynamoDB
  - ${file(../../resources/user-table.yml)}
  - Outputs:
      UserApiGatewayRestApi:
        Value:
          Ref: ApiGatewayRestApi
        Export:
          Name: ${self:custom.stage}-UserApiGatewayRestApi
